#!/usr/bin/env bash
# Builds localhost/wootc-e2e-windows-ssh:latest — the dockurr/windows image
# with sshd baked in (key-only auth, dedicated e2e keypair) so debug
# sessions can `ssh` straight into the container instead of nesting
# `podman exec` through heredocs (a real source of quoting bugs during
# E2E debugging).
#
# Recipe: pull the base image, run it with a harmless override entrypoint,
# install+configure openssh-server in that running container, wrap the
# original entrypoint (dockurr/windows's own `tini -s /run/entry.sh`, which
# this script does NOT modify) so sshd starts alongside it, then commit the
# result as a new image. Re-run this script any time the base image updates.
#
# REPRODUCIBILITY: apt packages are installed with --no-install-recommends
# and pinned via PACKAGES.pin (auto-generated on first build). The base
# image digest and exact installed package versions are recorded in the
# run log for attribution. A post-build smoke test verifies that swtpm
# can start and that the QGA python helper is present — a broken harness
# image is caught before it reaches a test run.
#
# Usage: bash tests/e2e/build-ssh-image.sh [keyfile]
#   keyfile defaults to ~/.ssh/wootc_e2e_ed25519 (created if missing).
#
# After building, run-e2e.sh / compose.yml pick it up automatically
# (compose.yml's `image:` defaults to this tag). Connect with:
#   ssh -i ~/.ssh/wootc_e2e_ed25519 -p 2222 root@localhost
# (see compose.yml's ports: mapping for the published SSH port).

set -Eeuo pipefail

# PINNED. `:latest` moved from v6.02 to v6.03 mid-session and swtpm stopped
# starting inside the container ("Waiting for TPM emulator to launch..." then
# "ERROR: TPM socket (/tmp/swtpm.sock) not found? Disabling TPM module"),
# so dockur silently ran QEMU WITHOUT a TPM and every Windows 11 case failed the
# "missing TPM 2.0 or Secure Boot" preflight (runs 30183222185, 30188615998 —
# container.log records the version on its first line). Windows 11 requires
# TPM 2.0, so an unpinned base can break the whole matrix without a wootc change.
# Bump deliberately, after a green run, not by surprise.
BASE_IMAGE="${WOOTC_E2E_BASE_IMAGE:-docker.io/dockurr/windows:6.02}"
TARGET_IMAGE="localhost/wootc-e2e-windows-ssh:latest"
KEYFILE="${1:-$HOME/.ssh/wootc_e2e_ed25519}"
BUILDER="wootc-ssh-builder"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PIN_FILE="$SCRIPT_DIR/PACKAGES.pin"
LOG_FILE="$SCRIPT_DIR/build-ssh-image.log"

if [[ ! -f "$KEYFILE" ]]; then
    echo "+ generating dedicated e2e keypair at $KEYFILE"
    ssh-keygen -t ed25519 -N "" -C "wootc-e2e-debug" -f "$KEYFILE"
fi

echo "+ pulling $BASE_IMAGE"
podman pull -q "$BASE_IMAGE" >/dev/null

podman rm -f "$BUILDER" >/dev/null 2>&1 || true
echo "+ starting builder container"
podman run -d --name "$BUILDER" --entrypoint sh "$BASE_IMAGE" -c "sleep infinity"

echo "+ installing openssh-server (--no-install-recommends)"

# Build the apt install command.  If a pin file exists (from a prior
# verified build), install exact package versions so the derived image
# is bit-for-bit reproducible across different build dates.
if [[ -f "$PIN_FILE" ]]; then
    echo "+   using pinned versions from $PIN_FILE"
    # Construct: apt-get install -y -qq --no-install-recommends pkg1=ver1 pkg2=ver2 ...
    pinned_pkgs=""
    while IFS= read -r line; do
        [[ -z "$line" || "$line" == '#'* ]] && continue
        pinned_pkgs="$pinned_pkgs $line"
    done < "$PIN_FILE"
    podman exec "$BUILDER" sh -c "apt-get update -qq && apt-get install -y -qq --no-install-recommends $pinned_pkgs >/dev/null"
else
    echo "+   no pin file; installing latest (pin file will be generated)"
    podman exec "$BUILDER" sh -c "apt-get update -qq && apt-get install -y -qq --no-install-recommends openssh-server >/dev/null"
fi

# ── Capture exact installed versions ─────────────────────────────────────
echo "+ capturing installed package versions"
INSTALLED_VERSIONS=$(podman exec "$BUILDER" sh -c \
    "dpkg-query -W -f='\${binary:Package}=\${Version}\n' openssh-server \$(dpkg-query -W -f='\${binary:Package}\n' openssh-server | xargs apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances -i openssh-server 2>/dev/null | grep '^[[:space:]]*Depends:' | sed 's/^[[:space:]]*Depends://' | sed 's/:.*//' | sort -u) 2>/dev/null | sort -u" || true)

# If no pin file exists, generate one from the freshly installed versions.
if [[ ! -f "$PIN_FILE" ]]; then
    echo "# Generated by build-ssh-image.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$PIN_FILE"
    echo "# Base image: $BASE_IMAGE" >> "$PIN_FILE"
    echo "$INSTALLED_VERSIONS" >> "$PIN_FILE"
    echo "+   wrote $PIN_FILE"
fi
podman exec "$BUILDER" ssh-keygen -A

# NOTE (#59): a swtpm wrapper and a tpmstate-path patch lived here. Neither
# fixed the GitHub-runner failure, and on self-hosted hosts — where stock dockur
# TPM works fine — they BROKE it (dilli dakota run, 2026-07-26: "missing TPM 2.0
# or Secure Boot" with the wrapper baked in, after the stock image had been
# verified working on the same box). Reverted: do not modify dockur's TPM path.
# #59 stays open as a GitHub-hosted-runner environment defect.

echo "+ installing authorized_keys (key-only auth)"
podman exec "$BUILDER" mkdir -p /root/.ssh
podman cp "${KEYFILE}.pub" "$BUILDER:/root/.ssh/authorized_keys"
podman exec "$BUILDER" sh -c "chmod 700 /root/.ssh && chmod 600 /root/.ssh/authorized_keys"
podman exec "$BUILDER" sh -c \
    "sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin prohibit-password/;s/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config"

echo "+ installing entrypoint wrapper (sshd, then chain to the original entrypoint unmodified)"
WRAPPER=$(mktemp)
cat << 'EOF' > "$WRAPPER"
#!/bin/sh
# NOTE (#59): tini must be PID 1, exactly as in stock dockur. This script is
# therefore started BY tini (see the ENTRYPOINT below) and runs entry.sh
# directly rather than nesting another tini. When this script was PID 1 itself,
# PID 1 was a plain shell with no init semantics, and dockur's swtpm — which
# daemonizes with -d — never wrote its pid file, so dockur silently disabled
# TPM and every Windows 11 case failed the preflight on EVERY host.
mkdir -p /run/sshd
/usr/sbin/sshd

while true; do
  rm -f /run/shm/qemu.end /run/shm/qemu.pid /run/shm/qemu.pty /run/shm/console.pid /run/shm/console.sock
  /run/entry.sh || true
  echo "[wootc-entrypoint] QEMU exited; restarting in 2 seconds..."
  sleep 2
done
EOF
podman cp "$WRAPPER" "$BUILDER:/usr/local/bin/wootc-entrypoint.sh"
rm -f "$WRAPPER"
podman exec "$BUILDER" chmod +x /usr/local/bin/wootc-entrypoint.sh

echo "+ committing $TARGET_IMAGE"
podman commit \
    --change 'ENTRYPOINT ["/usr/bin/tini","-s","--","/usr/local/bin/wootc-entrypoint.sh"]' \
    --change 'CMD []' \
    "$BUILDER" "$TARGET_IMAGE"
podman rm -f "$BUILDER" >/dev/null

# ── Record base digest and installed versions ────────────────────────────
BASE_DIGEST=$(podman image inspect --format '{{.Digest}}' "$BASE_IMAGE" 2>/dev/null || echo "unknown")
{
    echo "=== build-ssh-image.sh run log ==="
    echo "date:        $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "base_image:  $BASE_IMAGE"
    echo "base_digest: $BASE_DIGEST"
    echo "target:      $TARGET_IMAGE"
    echo ""
    echo "--- installed packages (dpkg versions) ---"
    echo "$INSTALLED_VERSIONS"
} > "$LOG_FILE"

# ── Post-build smoke test: assert harness capabilities ───────────────────
# The E2E harness requires swtpm (TPM emulator) and the QGA python helper.
# If either is missing a broken image will reach a test run and produce
# misleading failures.  Catch it here, loudly.
echo "+ post-build smoke test"
SMOKE_OK=true

# Verify swtpm binary exists and can start+bind a socket.
# Uses a one-shot swtpm that starts, binds, and terminates immediately —
# catches missing libraries or broken TPM emulation before a test run.
if podman run --rm --entrypoint "" "$TARGET_IMAGE" sh -c \
    'd=/tmp/swtpm-smoke-$$; mkdir -p "$d"; swtpm socket --tpm2 --tpmstate dir="$d" --server type=unixio,path="$d.sock" --ctrl type=unixio,path="$d-ctrl.sock" --terminate 2>/dev/null & sleep 2; test -S "$d.sock"; rc=$?; kill %1 2>/dev/null; rm -rf "$d" "$d.sock" "$d-ctrl.sock" 2>/dev/null; exit $rc' >/dev/null 2>&1; then
    echo "+   swtpm (start + bind socket): OK"
else
    echo "[FAIL] swtpm cannot start and bind a socket in the derived image — TPM emulation will fail" >&2
    SMOKE_OK=false
fi

# Verify the QGA python helper is present (used by run-e2e.sh).
if podman run --rm --entrypoint "" "$TARGET_IMAGE" test -f /run/entry.sh; then
    echo "+   dockur entry.sh: OK"
else
    echo "[FAIL] dockur entry.sh is missing in the derived image" >&2
    SMOKE_OK=false
fi

# Verify sshd can start and print its version.
if podman run --rm --entrypoint "" "$TARGET_IMAGE" sshd -t 2>/dev/null; then
    echo "+   sshd config test: OK"
else
    echo "[FAIL] sshd config test failed in the derived image" >&2
    SMOKE_OK=false
fi

if [[ "$SMOKE_OK" != "true" ]]; then
    echo "[FAIL] post-build smoke test failed — the derived image is broken and must not be used for E2E runs" >&2
    echo "  Remove $TARGET_IMAGE with: podman rmi $TARGET_IMAGE" >&2
    exit 1
fi
echo "+ post-build smoke test: PASS"

echo "+ done: $TARGET_IMAGE"
podman images "$TARGET_IMAGE"
echo
echo "Base image digest: $BASE_DIGEST"
echo "Build log:          $LOG_FILE"
echo "Package pin file:   $PIN_FILE"
echo
echo "Connect once the container is running (add \"2222:22\" to compose.yml's ports:):"
echo "  ssh -i $KEYFILE -p 2222 root@localhost"
