# Code generated by packaging/generate-steps.py; DO NOT EDIT.
# shellcheck shell=bash disable=SC2034
# Lifecycle states and recovery verdicts are distinct from these phase IDs.

WOOTC_INSTALLER_PHASE_IDS='Checking your PC
Preparing Windows
Setting things up
Finding your files
Making room for Linux
Downloading Linux
Downloading your Linux system
Preparing the startup menu
Getting Linux prepared
Making Linux bootable on your machine
Saving your settings
Saving your BitLocker recovery key
Looking at your installed apps
Checking your signed-in apps
Looking for your cloud drives
Collecting your look and Wi-Fi
Finishing up'
WOOTC_DEPLOYER_PHASE_IDS='ntfs-mounted
scratch-setup
network-wait
bundle-ingest
registry-preflight
fisherman
verification
reboot'
WOOTC_FIRSTBOOT_PHASE_IDS=firstboot-evidence

wootc_step_label() {
    case "$1" in
        'Checking your PC') printf '%s\n' 'Checking your PC' ;;
        'Preparing Windows') printf '%s\n' 'Preparing Windows' ;;
        'Setting things up') printf '%s\n' 'Setting things up' ;;
        'Finding your files') printf '%s\n' 'Finding your files' ;;
        'Making room for Linux') printf '%s\n' 'Making room for Linux' ;;
        'Downloading Linux') printf '%s\n' 'Downloading Linux' ;;
        'Downloading your Linux system') printf '%s\n' 'Downloading your Linux system' ;;
        'Preparing the startup menu') printf '%s\n' 'Preparing the startup menu' ;;
        'Getting Linux prepared') printf '%s\n' 'Getting Linux prepared' ;;
        'Making Linux bootable on your machine') printf '%s\n' 'Making Linux bootable on your machine' ;;
        'Saving your settings') printf '%s\n' 'Saving your settings' ;;
        'Saving your BitLocker recovery key') printf '%s\n' 'Saving your BitLocker recovery key' ;;
        'Looking at your installed apps') printf '%s\n' 'Looking at your installed apps' ;;
        'Checking your signed-in apps') printf '%s\n' 'Checking your signed-in apps' ;;
        'Looking for your cloud drives') printf '%s\n' 'Looking for your cloud drives' ;;
        'Collecting your look and Wi-Fi') printf '%s\n' 'Collecting your look and Wi-Fi' ;;
        'Finishing up') printf '%s\n' 'Finishing up' ;;
        ntfs-mounted) printf '%s\n' 'Preparing your disk...' ;;
        scratch-setup) printf '%s\n' 'Preparing your disk...' ;;
        network-wait) printf '%s\n' 'Waiting for a network connection - plug in a network cable if this takes a while...' ;;
        bundle-ingest) printf '%s\n' 'Loading your downloaded system - no internet needed...' ;;
        registry-preflight) printf '%s\n' 'Connecting to the software library...' ;;
        fisherman) printf '%s\n' 'Installing your Linux system...' ;;
        verification) printf '%s\n' 'Checking your Linux system...' ;;
        reboot) printf '%s\n' 'Preparing to restart...' ;;
        firstboot-evidence) printf '%s\n' 'Verifying your installed Linux boot...' ;;
        *) return 1 ;;
    esac
}

wootc_step_owner() {
    case "$1" in
        'Checking your PC') printf '%s\n' installer ;;
        'Preparing Windows') printf '%s\n' installer ;;
        'Setting things up') printf '%s\n' installer ;;
        'Finding your files') printf '%s\n' installer ;;
        'Making room for Linux') printf '%s\n' installer ;;
        'Downloading Linux') printf '%s\n' installer ;;
        'Downloading your Linux system') printf '%s\n' installer ;;
        'Preparing the startup menu') printf '%s\n' installer ;;
        'Getting Linux prepared') printf '%s\n' installer ;;
        'Making Linux bootable on your machine') printf '%s\n' installer ;;
        'Saving your settings') printf '%s\n' installer ;;
        'Saving your BitLocker recovery key') printf '%s\n' installer ;;
        'Looking at your installed apps') printf '%s\n' installer ;;
        'Checking your signed-in apps') printf '%s\n' installer ;;
        'Looking for your cloud drives') printf '%s\n' installer ;;
        'Collecting your look and Wi-Fi') printf '%s\n' installer ;;
        'Finishing up') printf '%s\n' installer ;;
        ntfs-mounted) printf '%s\n' deployer ;;
        scratch-setup) printf '%s\n' deployer ;;
        network-wait) printf '%s\n' deployer ;;
        bundle-ingest) printf '%s\n' deployer ;;
        registry-preflight) printf '%s\n' deployer ;;
        fisherman) printf '%s\n' deployer ;;
        verification) printf '%s\n' deployer ;;
        reboot) printf '%s\n' deployer ;;
        firstboot-evidence) printf '%s\n' firstboot ;;
        *) return 1 ;;
    esac
}

wootc_step_valid() { wootc_step_owner "$1" >/dev/null; }

# All actual deployer phase announcements, not liveness or completion proof.
WOOTC_DEPLOYER_PHASE_MARKERS='phase: (ntfs-mounted|scratch-setup|network-wait|bundle-ingest|registry-preflight|fisherman|verification|reboot)([[:space:]]|$)'
WOOTC_FIRSTBOOT_PHASE_MARKERS='phase: (firstboot-evidence)([[:space:]]|$)'
