// <auto-generated>
// This code was generated by go generate (app/tools/gendto).
// Do not edit this file directly.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Wootc.Shell.Engine;

/// <summary>
/// SupportPolicy is what the current release channel allows. The frontend
/// reads it to gate the UI to green-only scenarios (docs/RELEASING.md); the
/// backend enforces the same rules in StartInstall (defense in depth).
/// </summary>
public class SupportPolicy
{
    /// <summary>
    /// alpha | beta | stable
    /// </summary>
    [JsonPropertyName("channel")]
    public string Channel { get; set; } = string.Empty;

    /// <summary>
    /// offer non-green images?
    /// </summary>
    [JsonPropertyName("experimentalImages")]
    public bool ExperimentalImages { get; set; }

    /// <summary>
    /// is the FDE path green yet? (#34)
    /// </summary>
    [JsonPropertyName("bitlockerSupported")]
    public bool BitlockerSupported { get; set; }

    /// <summary>
    /// arbitrary OCI ref?
    /// </summary>
    [JsonPropertyName("customImageAllowed")]
    public bool CustomImageAllowed { get; set; }

    /// <summary>
    /// one-liner for the UI
    /// </summary>
    [JsonPropertyName("reason")]
    public string Reason { get; set; } = string.Empty;
}

/// <summary>
/// SystemInfo describes the host Windows environment.
/// </summary>
public class SystemInfo
{
    [JsonPropertyName("osVersion")]
    public string OsVersion { get; set; } = string.Empty;

    [JsonPropertyName("freeDiskGB")]
    public double FreeDiskGB { get; set; }

    [JsonPropertyName("totalDiskGB")]
    public double TotalDiskGB { get; set; }

    [JsonPropertyName("bitLockerOn")]
    public bool BitLockerOn { get; set; }

    /// <summary>
    /// BitLockerState is the detailed C: encryption state (SPEC §3.5):
    /// "off" | "on" | "encrypting" | "decrypting". "encrypting" is a hard
    /// block; "on" offers the data-partition path.
    /// </summary>
    [JsonPropertyName("bitLockerState")]
    public string BitLockerState { get; set; } = string.Empty;

    [JsonPropertyName("fastStartupOn")]
    public bool FastStartupOn { get; set; }

    [JsonPropertyName("isUefi")]
    public bool IsUefi { get; set; }

    [JsonPropertyName("secureBootOn")]
    public bool SecureBootOn { get; set; }

    [JsonPropertyName("secureBootKnown")]
    public bool SecureBootKnown { get; set; }

    /// <summary>
    /// DefragRecommended is advisory only. Fragmentation affects VHDX
    /// performance on rotating media, not correctness (SPEC §3.6).
    /// </summary>
    [JsonPropertyName("defragRecommended")]
    public bool DefragRecommended { get; set; }

    /// <summary>
    /// ── Preflight safety gates (#63) ──────────────────────────────────────
    /// Conditions under which starting a migration risks the user's data or
    /// leaves the machine half-converted. Each is reported separately so the
    /// GUI can name the ONE thing standing in the way rather than a generic
    /// "cannot install".
    /// OnBattery: a migration interrupted by a flat battery mid-shrink is the
    /// worst possible moment to lose power.
    /// </summary>
    [JsonPropertyName("onBattery")]
    public bool OnBattery { get; set; }

    /// <summary>
    /// BatteryKnown is false on desktops and where the query failed; only an
    /// affirmative "running on battery" should ever block.
    /// </summary>
    [JsonPropertyName("batteryKnown")]
    public bool BatteryKnown { get; set; }

    /// <summary>
    /// PendingReboot: a servicing operation can rewrite boot configuration
    /// underneath us, or resume in the middle of the migration. Narrow by
    /// design — see pendingReboot() for why PendingFileRenameOperations is
    /// deliberately NOT one of the signals.
    /// </summary>
    [JsonPropertyName("pendingReboot")]
    public bool PendingReboot { get; set; }

    /// <summary>
    /// PendingRebootReason names the signal that fired ("servicing",
    /// "windows-update"), so a refusal can be argued with rather than guessed at.
    /// </summary>
    [JsonPropertyName("pendingRebootReason")]
    public string PendingRebootReason { get; set; } = string.Empty;

    /// <summary>
    /// Hibernated: hiberfil.sys present means the NTFS in-memory state is
    /// newer than the disk. Mounting that read-write from Linux is exactly
    /// how NTFS gets corrupted — the data loss wootc exists to prevent.
    /// </summary>
    [JsonPropertyName("hibernated")]
    public bool Hibernated { get; set; }

    /// <summary>
    /// RAMGB and Is64Bit gate hardware that cannot run the result.
    /// </summary>
    [JsonPropertyName("ramGB")]
    public double RamGB { get; set; }

    [JsonPropertyName("is64Bit")]
    public bool Is64Bit { get; set; }

    /// <summary>
    /// DataPartitions lists unencrypted fixed volumes (other than C:) that
    /// could hold root.disk when C: is BitLocker-protected.
    /// </summary>
    [JsonPropertyName("dataPartitions")]
    public List<DataPartition> DataPartitions { get; set; } = new();

    /// <summary>
    /// BitLockerRecoveryKeyWarning is true when BitLocker ProtectionStatus is
    /// On and the user should record their recovery key before proceeding (#63).
    /// This is honest disclosure, independent of whether we unlock C: (#61).
    /// </summary>
    [JsonPropertyName("bitLockerRecoveryKeyWarning")]
    public bool BitLockerRecoveryKeyWarning { get; set; }

    /// <summary>
    /// SuggestedHostname is this Windows machine's name, sanitised into a
    /// legal Linux hostname, so the migrated system keeps the identity the
    /// user already knows instead of a generic default (#174). Empty when the
    /// name could not be read or sanitises to nothing; the GUI then falls back
    /// to its own default rather than showing a blank field.
    /// </summary>
    [JsonPropertyName("suggestedHostname")]
    public string SuggestedHostname { get; set; } = string.Empty;

    /// <summary>
    /// SuggestedUsername is the signed-in Windows account name, sanitised into
    /// a legal Linux username, so the migrated system keeps the identity the
    /// user already has. Empty when unreadable or when nothing usable
    /// survives; the GUI then leaves the field for the user to fill.
    /// </summary>
    [JsonPropertyName("suggestedUsername")]
    public string SuggestedUsername { get; set; } = string.Empty;

    /// <summary>
    /// TrustedUefiAuthorities lists the Microsoft UEFI CA generations this
    /// machine's firmware holds in its db variable ("2011", "2023"), so the
    /// preflight can tell before the reboot whether the signed shim this
    /// build stages will be launched at all (#322). Empty means the db could
    /// not be read, which warns rather than refusing.
    /// </summary>
    [JsonPropertyName("trustedUefiAuthorities")]
    public List<string> TrustedUefiAuthorities { get; set; } = new();

    /// <summary>
    /// SecureBootChainWarning is set when Secure Boot is on but the db could
    /// not be read: honest disclosure that one check could not be made,
    /// shown before the user commits rather than after the restart.
    /// </summary>
    [JsonPropertyName("secureBootChainWarning")]
    public string SecureBootChainWarning { get; set; } = string.Empty;
}

/// <summary>
/// DataPartition is a candidate unencrypted volume for root.disk.
/// </summary>
public class DataPartition
{
    [JsonPropertyName("letter")]
    public string Letter { get; set; } = string.Empty;

    [JsonPropertyName("label")]
    public string Label { get; set; } = string.Empty;

    [JsonPropertyName("freeGB")]
    public double FreeGB { get; set; }

    [JsonPropertyName("encrypted")]
    public bool Encrypted { get; set; }
}

/// <summary>
/// Branding lets partners ship a re-skinned migrator: product name,
/// tagline, logo emoji, and a color palette applied as CSS variables at
/// runtime. The frontend calls GetBranding() on startup.
/// </summary>
public class Branding
{
    /// <summary>
    /// Name is the distribution being installed ("TunaOS", "Bazzite") — what
    /// the screens, the boot menu, and Add/Remove Programs call the result.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("tagline")]
    public string Tagline { get; set; } = string.Empty;

    [JsonPropertyName("logoEmoji")]
    public string LogoEmoji { get; set; } = string.Empty;

    [JsonPropertyName("version")]
    public string Version { get; set; } = string.Empty;

    /// <summary>
    /// primary action / highlight
    /// </summary>
    [JsonPropertyName("accent")]
    public string Accent { get; set; } = string.Empty;

    /// <summary>
    /// text on accent (contrast)
    /// </summary>
    [JsonPropertyName("accentText")]
    public string AccentText { get; set; } = string.Empty;

    [JsonPropertyName("background")]
    public string Background { get; set; } = string.Empty;

    [JsonPropertyName("card")]
    public string Card { get; set; } = string.Empty;

    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;

    /// <summary>
    /// InstallVerb personalizes CTA copy ("Install", "Migrate", "Switch").
    /// </summary>
    [JsonPropertyName("installVerb")]
    public string InstallVerb { get; set; } = string.Empty;

    /// <summary>
    /// ProductName is the installer's own name (window title, title bar,
    /// "run &lt;product&gt; again" copy). The generic build is "wootc"; branded
    /// builds never surface that word (docs/branding-and-distribution.md).
    /// </summary>
    [JsonPropertyName("productName")]
    public string ProductName { get; set; } = string.Empty;

    /// <summary>
    /// ExeName names the release asset ("Bazzite-Installer" → .exe). Consumed
    /// by the release workflow, carried here so one file defines a brand.
    /// </summary>
    [JsonPropertyName("exeName")]
    public string ExeName { get; set; } = string.Empty;

    /// <summary>
    /// Catalog restricts the offered images to these ids from images.json, in
    /// this order. Empty = the full (channel-gated) catalog.
    /// </summary>
    [JsonPropertyName("catalog")]
    public List<string> Catalog { get; set; } = new();

    /// <summary>
    /// DefaultImage pre-selects a catalog entry on the launchpad.
    /// </summary>
    [JsonPropertyName("defaultImage")]
    public string DefaultImage { get; set; } = string.Empty;

    /// <summary>
    /// HideCustomImage removes the custom-OCI field regardless of channel:
    /// a branded installer installs its own distribution, nothing else.
    /// </summary>
    [JsonPropertyName("hideCustomImage")]
    public bool HideCustomImage { get; set; }

    /// <summary>
    /// PreloadImage asks the app to download the OCI image on Windows so the
    /// deployer never needs the network (laptops have no Wi-Fi in the
    /// initramfs — docs/branding-and-distribution.md §3).
    /// </summary>
    [JsonPropertyName("preloadImage")]
    public bool PreloadImage { get; set; }

    /// <summary>
    /// Real brand assets (deep branding). LogoDataURI replaces the emoji
    /// wherever a mark renders; FontDataURI + FontFamily bring the brand's
    /// actual typeface (embedded, never fetched); ThemeCSS is injected after
    /// style.css and restyles tokens and components (buttons, radii, palette).
    /// Populated from the embedded brand directory; an enterprise overlay may
    /// supply logoDataUri inline in brand.json and CSS via C:\wootc\brand.css.
    /// </summary>
    [JsonPropertyName("fontFamily")]
    public string FontFamily { get; set; } = string.Empty;

    [JsonPropertyName("logoDataUri")]
    public string LogoDataUri { get; set; } = string.Empty;

    [JsonPropertyName("fontDataUri")]
    public string FontDataUri { get; set; } = string.Empty;

    [JsonPropertyName("themeCss")]
    public string ThemeCss { get; set; } = string.Empty;
}

/// <summary>
/// Image is one bootable variant from the catalog.
/// </summary>
public class Image
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("emoji")]
    public string Emoji { get; set; } = string.Empty;

    [JsonPropertyName("base")]
    public string Base { get; set; } = string.Empty;

    [JsonPropertyName("desktop")]
    public string Desktop { get; set; } = string.Empty;

    [JsonPropertyName("desktopName")]
    public string DesktopName { get; set; } = string.Empty;

    [JsonPropertyName("imageRef")]
    public string ImageRef { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// grub2 | systemd-boot
    /// </summary>
    [JsonPropertyName("bootloader")]
    public string Bootloader { get; set; } = string.Empty;

    [JsonPropertyName("composeFs")]
    public bool ComposeFs { get; set; }

    /// <summary>
    /// el10 | fedora | arch | debian | custom
    /// </summary>
    [JsonPropertyName("family")]
    public string Family { get; set; } = string.Empty;

    /// <summary>
    /// Status gates what a release channel offers (docs/RELEASING.md):
    /// "green"        — proven end-to-end by the E2E matrix; offered in every channel
    /// "experimental" — builds/works but not yet E2E-green; hidden in alpha
    /// Empty is treated as "experimental" (fail safe — never surface an
    /// unproven image to an alpha user by omission).
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>
    /// MokEnroll is the MokManager password for images whose custom kernel
    /// needs the distribution's MOK key enrolled under Secure Boot (#248).
    /// Non-empty means: the deployer queues the enrollment, and the GUI warns
    /// the user about the one-time blue MokManager screen with this password.
    /// </summary>
    [JsonPropertyName("mokEnroll")]
    public string? MokEnroll { get; set; }
}

/// <summary>
/// InstallConfig is the parameters collected on Screen 1.
/// </summary>
public class InstallConfig
{
    [JsonPropertyName("imageRef")]
    public string ImageRef { get; set; } = string.Empty;

    [JsonPropertyName("diskSizeGB")]
    public int DiskSizeGB { get; set; }

    [JsonPropertyName("username")]
    public string Username { get; set; } = string.Empty;

    [JsonPropertyName("password")]
    public string Password { get; set; } = string.Empty;

    [JsonPropertyName("hostname")]
    public string Hostname { get; set; } = string.Empty;

    /// <summary>
    /// Bootloader is the deployer boot chain: "auto" (default; the deployer
    /// probes the image and picks the backend), "grub2" or "systemd-boot"
    /// (explicit Advanced overrides).
    /// </summary>
    [JsonPropertyName("bootloader")]
    public string Bootloader { get; set; } = string.Empty;

    [JsonPropertyName("composeFs")]
    public bool ComposeFs { get; set; }

    /// <summary>
    /// StorageDrive is the drive letter (no colon) where root.disk + vault
    /// live. Empty means C:. On a BitLocker-protected C:, the GUI sets this
    /// to an unencrypted data volume so the deployer can mount it read-write
    /// every boot without a decryption prompt (SPEC §3.5). C: stays encrypted.
    /// </summary>
    [JsonPropertyName("storageDrive")]
    public string StorageDrive { get; set; } = string.Empty;

    /// <summary>
    /// Encryption for the Linux root inside root.disk (SPEC §2.6):
    /// "none" | "tpm2-luks" (auto-unlock via TPM, recommended) |
    /// "luks-passphrase" (prompt every boot).
    /// </summary>
    [JsonPropertyName("encryption")]
    public string Encryption { get; set; } = string.Empty;

    [JsonPropertyName("luksPassphrase")]
    public string LuksPassphrase { get; set; } = string.Empty;

    /// <summary>
    /// WindowsLook opts into Windows-Style Mode (SPEC §4.4): bring the user's
    /// wallpaper, accent, keyboard layout, taskbar pins and desktop shortcuts
    /// over on first login. Default false — we honor the image maker's desktop
    /// defaults unless the user asks to make it feel like Windows.
    /// </summary>
    [JsonPropertyName("windowsLook")]
    public bool WindowsLook { get; set; }

    /// <summary>
    /// SessionConsent is opt-in per app because it authorizes moving auth
    /// material. An absent or false entry never stages a session envelope.
    /// </summary>
    [JsonPropertyName("sessionConsent")]
    public Dictionary<string, bool>? SessionConsent { get; set; }
}

/// <summary>
/// ProgressEvent is emitted during install for the frontend progress bar.
/// </summary>
public class ProgressEvent
{
    [JsonPropertyName("step")]
    public string Step { get; set; } = string.Empty;

    [JsonPropertyName("message")]
    public string Message { get; set; } = string.Empty;

    [JsonPropertyName("percent")]
    public double Percent { get; set; }

    [JsonPropertyName("done")]
    public bool Done { get; set; }

    [JsonPropertyName("error")]
    public string? Error { get; set; }
}

/// <summary>
/// InstallStatus is the current state of a running or completed install.
/// </summary>
public class InstallStatus
{
    [JsonPropertyName("running")]
    public bool Running { get; set; }

    [JsonPropertyName("done")]
    public bool Done { get; set; }

    [JsonPropertyName("error")]
    public string? Error { get; set; }

    /// <summary>
    /// root.vhdx already found on startup
    /// </summary>
    [JsonPropertyName("existing")]
    public bool Existing { get; set; }
}

/// <summary>
/// UninstallInfo describes an existing install so the uninstaller can offer
/// the right options (SPEC §5): where root.disk lives and whether that
/// volume was created by wootc (and is therefore safe to remove entirely).
/// </summary>
public class UninstallInfo
{
    [JsonPropertyName("found")]
    public bool Found { get; set; }

    /// <summary>
    /// where root.disk lives
    /// </summary>
    [JsonPropertyName("storageDrive")]
    public string StorageDrive { get; set; } = string.Empty;

    /// <summary>
    /// full path to root.disk
    /// </summary>
    [JsonPropertyName("diskPath")]
    public string DiskPath { get; set; } = string.Empty;

    [JsonPropertyName("diskSizeGB")]
    public double DiskSizeGB { get; set; }

    /// <summary>
    /// wootc-created data partition
    /// </summary>
    [JsonPropertyName("onDedicatedVol")]
    public bool OnDedicatedVol { get; set; }

    /// <summary>
    /// space freed if the volume is removed
    /// </summary>
    [JsonPropertyName("reclaimGB")]
    public double ReclaimGB { get; set; }

    /// <summary>
    /// verified volume label (e.g. "wootc-data")
    /// </summary>
    [JsonPropertyName("volumeLabel")]
    public string? VolumeLabel { get; set; }

    /// <summary>
    /// Orphaned: no root.disk anywhere, but leftover boot arming (bcd-guid /
    /// state.json) exists — the "user deleted the folder by hand" case, which
    /// previously had NO GUI path to clean up the boot entry.
    /// </summary>
    [JsonPropertyName("orphaned")]
    public bool Orphaned { get; set; }

    /// <summary>
    /// Deployed: the deployer has completed at least once (its staged journal
    /// exists, or the lifecycle state says deployed/healthy) — so this PC has
    /// a bootable TunaOS and the control panel can offer to restart into it.
    /// </summary>
    [JsonPropertyName("deployed")]
    public bool Deployed { get; set; }
}

/// <summary>
/// UninstallOptions controls how much the uninstaller removes (SPEC §5).
/// </summary>
public class UninstallOptions
{
    /// <summary>
    /// delete root.disk (loses Linux data)
    /// </summary>
    [JsonPropertyName("deleteRootDisk")]
    public bool DeleteRootDisk { get; set; }

    /// <summary>
    /// remove the wootc data partition, extend C:
    /// </summary>
    [JsonPropertyName("removePartition")]
    public bool RemovePartition { get; set; }
}

/// <summary>
/// LifecycleState is the persisted contents of state.json.
/// </summary>
public class LifecycleState
{
    [JsonPropertyName("state")]
    public string State { get; set; } = string.Empty;

    /// <summary>
    /// failing step/phase when failed
    /// </summary>
    [JsonPropertyName("phase")]
    public string? Phase { get; set; }

    [JsonPropertyName("error")]
    public string? Error { get; set; }

    [JsonPropertyName("updatedAt")]
    public string UpdatedAt { get; set; } = string.Empty;

    [JsonPropertyName("updatedBy")]
    public string UpdatedBy { get; set; } = string.Empty;
}

/// <summary>
/// SessionCandidate is a per-app finding surfaced to the GUI so the user can
/// consent (or not) to moving its login. It contains no token material.
/// </summary>
public class SessionCandidate
{
    [JsonPropertyName("app")]
    public string App { get; set; } = string.Empty;

    /// <summary>
    /// "chromium" | "plainfile"
    /// </summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    /// <summary>
    /// decryptable here?
    /// </summary>
    [JsonPropertyName("portable")]
    public bool Portable { get; set; }

    /// <summary>
    /// "copy" | "relink" | "signin"
    /// </summary>
    [JsonPropertyName("recommend")]
    public string Recommend { get; set; } = string.Empty;

    [JsonPropertyName("note")]
    public string Note { get; set; } = string.Empty;

    [JsonPropertyName("consentRequired")]
    public bool ConsentRequired { get; set; }
}

/// <summary>
/// SessionExport records the honest state of the online half of a session
/// migration. "staged" means only that an authenticated envelope containing
/// the app key was written; it is not a claim that the Linux app is signed in.
/// </summary>
public class SessionExport
{
    [JsonPropertyName("app")]
    public string App { get; set; } = string.Empty;

    /// <summary>
    /// staged | skipped | failed
    /// </summary>
    [JsonPropertyName("state")]
    public string State { get; set; } = string.Empty;

    [JsonPropertyName("reason")]
    public string? Reason { get; set; }
}

/// <summary>
/// VMEvent is a Try-in-VM progress event (frontend listens on "vm:progress").
/// </summary>
public class VMEvent
{
    /// <summary>
    /// pulling | installing | booting | ready | error
    /// </summary>
    [JsonPropertyName("stage")]
    public string Stage { get; set; } = string.Empty;

    [JsonPropertyName("percent")]
    public double Percent { get; set; }

    [JsonPropertyName("message")]
    public string Message { get; set; } = string.Empty;
}

/// <summary>
/// VMCapability tells the GUI whether "Boot in VM" can run and why not.
/// </summary>
public class VMCapability
{
    [JsonPropertyName("available")]
    public bool Available { get; set; }

    [JsonPropertyName("reason")]
    public string Reason { get; set; } = string.Empty;

    [JsonPropertyName("diskPath")]
    public string DiskPath { get; set; } = string.Empty;

    [JsonPropertyName("accelerator")]
    public string Accelerator { get; set; } = string.Empty;

    [JsonPropertyName("qemuPath")]
    public string QemuPath { get; set; } = string.Empty;

    [JsonPropertyName("bundled")]
    public bool Bundled { get; set; }
}

/// <summary>
/// BundleInfo describes a staged offline image bundle. Written by
/// payload/bundle/make-bundle.sh as bundle.json.
/// </summary>
public class BundleInfo
{
    /// <summary>
    /// Image is the reference the store holds, e.g. ghcr.io/tuna-os/dakota:latest.
    /// </summary>
    [JsonPropertyName("image")]
    public string Image { get; set; } = string.Empty;

    /// <summary>
    /// Digest pins exactly what will be installed. A tag can be re-pointed
    /// upstream, so someone installing offline months later needs this to know
    /// what they are actually booting.
    /// </summary>
    [JsonPropertyName("digest")]
    public string Digest { get; set; } = string.Empty;

    /// <summary>
    /// StoreBytes is the on-disk size, for showing the user what the bundle
    /// saves them downloading.
    /// </summary>
    [JsonPropertyName("storeBytes")]
    public long StoreBytes { get; set; }

    [JsonPropertyName("createdAt")]
    public string CreatedAt { get; set; } = string.Empty;

    /// <summary>
    /// Source distinguishes how the bundle got here: "" for a bundle shipped
    /// beside the installer (make-bundle.sh), "predownload" for one the app
    /// pulled itself for the offline deploy (ocipull.go). A shipped bundle
    /// pins the catalog to its one image (#177); a pre-download must NOT —
    /// it records a choice, it doesn't remove the others.
    /// </summary>
    [JsonPropertyName("source")]
    public string? Source { get; set; }
}
