// Code generated by packaging/generate-steps.py; DO NOT EDIT.
package main

type StepDefinition struct {
	ID    string `json:"id"`
	Owner string `json:"owner"`
	Label string `json:"label"`
}

const (
	StepInstallerCheckingYourPC                   = "Checking your PC"
	StepInstallerPreparingWindows                 = "Preparing Windows"
	StepInstallerSettingThingsUp                  = "Setting things up"
	StepInstallerFindingYourFiles                 = "Finding your files"
	StepInstallerMakingRoomForLinux               = "Making room for Linux"
	StepInstallerDownloadingLinux                 = "Downloading Linux"
	StepInstallerDownloadingYourLinuxSystem       = "Downloading your Linux system"
	StepInstallerPreparingTheStartupMenu          = "Preparing the startup menu"
	StepInstallerGettingLinuxPrepared             = "Getting Linux prepared"
	StepInstallerMakingLinuxBootableOnYourMachine = "Making Linux bootable on your machine"
	StepInstallerSavingYourSettings               = "Saving your settings"
	StepInstallerSavingYourBitLockerRecoveryKey   = "Saving your BitLocker recovery key"
	StepInstallerLookingAtYourInstalledApps       = "Looking at your installed apps"
	StepInstallerCheckingYourSignedInApps         = "Checking your signed-in apps"
	StepInstallerLookingForYourCloudDrives        = "Looking for your cloud drives"
	StepInstallerCollectingYourLookAndWiFi        = "Collecting your look and Wi-Fi"
	StepInstallerFinishingUp                      = "Finishing up"
	StepDeployerNtfsMounted                       = "ntfs-mounted"
	StepDeployerScratchSetup                      = "scratch-setup"
	StepDeployerNetworkWait                       = "network-wait"
	StepDeployerBundleIngest                      = "bundle-ingest"
	StepDeployerRegistryPreflight                 = "registry-preflight"
	StepDeployerFisherman                         = "fisherman"
	StepDeployerVerification                      = "verification"
	StepDeployerReboot                            = "reboot"
	StepFirstbootFirstbootEvidence                = "firstboot-evidence"
)

// StepCatalogue returns a fresh copy; callers cannot modify the authority.
func StepCatalogue() []StepDefinition {
	return []StepDefinition{
		{ID: StepInstallerCheckingYourPC, Owner: "installer", Label: "Checking your PC"},
		{ID: StepInstallerPreparingWindows, Owner: "installer", Label: "Preparing Windows"},
		{ID: StepInstallerSettingThingsUp, Owner: "installer", Label: "Setting things up"},
		{ID: StepInstallerFindingYourFiles, Owner: "installer", Label: "Finding your files"},
		{ID: StepInstallerMakingRoomForLinux, Owner: "installer", Label: "Making room for Linux"},
		{ID: StepInstallerDownloadingLinux, Owner: "installer", Label: "Downloading Linux"},
		{ID: StepInstallerDownloadingYourLinuxSystem, Owner: "installer", Label: "Downloading your Linux system"},
		{ID: StepInstallerPreparingTheStartupMenu, Owner: "installer", Label: "Preparing the startup menu"},
		{ID: StepInstallerGettingLinuxPrepared, Owner: "installer", Label: "Getting Linux prepared"},
		{ID: StepInstallerMakingLinuxBootableOnYourMachine, Owner: "installer", Label: "Making Linux bootable on your machine"},
		{ID: StepInstallerSavingYourSettings, Owner: "installer", Label: "Saving your settings"},
		{ID: StepInstallerSavingYourBitLockerRecoveryKey, Owner: "installer", Label: "Saving your BitLocker recovery key"},
		{ID: StepInstallerLookingAtYourInstalledApps, Owner: "installer", Label: "Looking at your installed apps"},
		{ID: StepInstallerCheckingYourSignedInApps, Owner: "installer", Label: "Checking your signed-in apps"},
		{ID: StepInstallerLookingForYourCloudDrives, Owner: "installer", Label: "Looking for your cloud drives"},
		{ID: StepInstallerCollectingYourLookAndWiFi, Owner: "installer", Label: "Collecting your look and Wi-Fi"},
		{ID: StepInstallerFinishingUp, Owner: "installer", Label: "Finishing up"},
		{ID: StepDeployerNtfsMounted, Owner: "deployer", Label: "Preparing your disk..."},
		{ID: StepDeployerScratchSetup, Owner: "deployer", Label: "Preparing your disk..."},
		{ID: StepDeployerNetworkWait, Owner: "deployer", Label: "Waiting for a network connection - plug in a network cable if this takes a while..."},
		{ID: StepDeployerBundleIngest, Owner: "deployer", Label: "Loading your downloaded system - no internet needed..."},
		{ID: StepDeployerRegistryPreflight, Owner: "deployer", Label: "Connecting to the software library..."},
		{ID: StepDeployerFisherman, Owner: "deployer", Label: "Installing your Linux system..."},
		{ID: StepDeployerVerification, Owner: "deployer", Label: "Checking your Linux system..."},
		{ID: StepDeployerReboot, Owner: "deployer", Label: "Preparing to restart..."},
		{ID: StepFirstbootFirstbootEvidence, Owner: "firstboot", Label: "Verifying your installed Linux boot..."},
	}
}

func InstallerSteps() []StepDefinition {
	var steps []StepDefinition
	for _, step := range StepCatalogue() {
		if step.Owner == "installer" {
			steps = append(steps, step)
		}
	}
	return steps
}

func StepLabel(id string) (string, bool) {
	switch id {
	case StepInstallerCheckingYourPC:
		return "Checking your PC", true
	case StepInstallerPreparingWindows:
		return "Preparing Windows", true
	case StepInstallerSettingThingsUp:
		return "Setting things up", true
	case StepInstallerFindingYourFiles:
		return "Finding your files", true
	case StepInstallerMakingRoomForLinux:
		return "Making room for Linux", true
	case StepInstallerDownloadingLinux:
		return "Downloading Linux", true
	case StepInstallerDownloadingYourLinuxSystem:
		return "Downloading your Linux system", true
	case StepInstallerPreparingTheStartupMenu:
		return "Preparing the startup menu", true
	case StepInstallerGettingLinuxPrepared:
		return "Getting Linux prepared", true
	case StepInstallerMakingLinuxBootableOnYourMachine:
		return "Making Linux bootable on your machine", true
	case StepInstallerSavingYourSettings:
		return "Saving your settings", true
	case StepInstallerSavingYourBitLockerRecoveryKey:
		return "Saving your BitLocker recovery key", true
	case StepInstallerLookingAtYourInstalledApps:
		return "Looking at your installed apps", true
	case StepInstallerCheckingYourSignedInApps:
		return "Checking your signed-in apps", true
	case StepInstallerLookingForYourCloudDrives:
		return "Looking for your cloud drives", true
	case StepInstallerCollectingYourLookAndWiFi:
		return "Collecting your look and Wi-Fi", true
	case StepInstallerFinishingUp:
		return "Finishing up", true
	case StepDeployerNtfsMounted:
		return "Preparing your disk...", true
	case StepDeployerScratchSetup:
		return "Preparing your disk...", true
	case StepDeployerNetworkWait:
		return "Waiting for a network connection - plug in a network cable if this takes a while...", true
	case StepDeployerBundleIngest:
		return "Loading your downloaded system - no internet needed...", true
	case StepDeployerRegistryPreflight:
		return "Connecting to the software library...", true
	case StepDeployerFisherman:
		return "Installing your Linux system...", true
	case StepDeployerVerification:
		return "Checking your Linux system...", true
	case StepDeployerReboot:
		return "Preparing to restart...", true
	case StepFirstbootFirstbootEvidence:
		return "Verifying your installed Linux boot...", true
	default:
		return "", false
	}
}

func StepOwner(id string) (string, bool) {
	switch id {
	case StepInstallerCheckingYourPC:
		return "installer", true
	case StepInstallerPreparingWindows:
		return "installer", true
	case StepInstallerSettingThingsUp:
		return "installer", true
	case StepInstallerFindingYourFiles:
		return "installer", true
	case StepInstallerMakingRoomForLinux:
		return "installer", true
	case StepInstallerDownloadingLinux:
		return "installer", true
	case StepInstallerDownloadingYourLinuxSystem:
		return "installer", true
	case StepInstallerPreparingTheStartupMenu:
		return "installer", true
	case StepInstallerGettingLinuxPrepared:
		return "installer", true
	case StepInstallerMakingLinuxBootableOnYourMachine:
		return "installer", true
	case StepInstallerSavingYourSettings:
		return "installer", true
	case StepInstallerSavingYourBitLockerRecoveryKey:
		return "installer", true
	case StepInstallerLookingAtYourInstalledApps:
		return "installer", true
	case StepInstallerCheckingYourSignedInApps:
		return "installer", true
	case StepInstallerLookingForYourCloudDrives:
		return "installer", true
	case StepInstallerCollectingYourLookAndWiFi:
		return "installer", true
	case StepInstallerFinishingUp:
		return "installer", true
	case StepDeployerNtfsMounted:
		return "deployer", true
	case StepDeployerScratchSetup:
		return "deployer", true
	case StepDeployerNetworkWait:
		return "deployer", true
	case StepDeployerBundleIngest:
		return "deployer", true
	case StepDeployerRegistryPreflight:
		return "deployer", true
	case StepDeployerFisherman:
		return "deployer", true
	case StepDeployerVerification:
		return "deployer", true
	case StepDeployerReboot:
		return "deployer", true
	case StepFirstbootFirstbootEvidence:
		return "firstboot", true
	default:
		return "", false
	}
}
