#!/usr/bin/env python3
"""Generate all phase vocabulary from payload/steps.tsv; --check never writes."""
import argparse
import difflib
import json
from pathlib import Path
import re
import shlex
import subprocess
import sys

OWNERS = ('installer', 'deployer', 'firstboot')


def read_catalogue(path):
    rows = []
    ids = set()
    symbols = set()
    for number, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
        if not line or line.startswith('#'):
            continue
        fields = line.split('\t')
        if len(fields) != 3:
            raise ValueError(f'{path}:{number}: expected exactly id, owner, label')
        phase_id, owner, label = fields
        if phase_id != phase_id.strip() or not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9 -]{0,127}', phase_id):
            raise ValueError(f'{path}:{number}: invalid phase ID')
        if owner not in OWNERS or not label or len(label) > 1024 or any(ord(c) < 32 for c in label):
            raise ValueError(f'{path}:{number}: invalid owner or label')
        symbol = 'Step' + owner.title() + ''.join(word[0].upper() + word[1:] for word in re.split(r'[ -]+', phase_id))
        if phase_id in ids or symbol in symbols:
            raise ValueError(f'{path}:{number}: duplicate ID or generated symbol')
        ids.add(phase_id)
        symbols.add(symbol)
        rows.append({'id': phase_id, 'owner': owner, 'label': label, 'symbol': symbol})
    if not rows or any(not any(row['owner'] == owner for row in rows) for owner in OWNERS):
        raise ValueError('catalogue must include installer, deployer and firstboot phases')
    return rows


def go_source(rows):
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    lines = ['// Code generated by packaging/generate-steps.py; DO NOT EDIT.', 'package main', '',
             'type StepDefinition struct {', '\tID string `json:"id"`', '\tOwner string `json:"owner"`',
             '\tLabel string `json:"label"`', '}', '', 'const (']
    lines += [f'\t{r["symbol"]} = {quote(r["id"])}' for r in rows]
    lines += [')', '', '// StepCatalogue returns a fresh copy; callers cannot modify the authority.',
              'func StepCatalogue() []StepDefinition {', '\treturn []StepDefinition{']
    lines += [f'\t\t{{ID: {r["symbol"]}, Owner: {quote(r["owner"])}, Label: {quote(r["label"])}}},' for r in rows]
    lines += ['\t}', '}', '', 'func InstallerSteps() []StepDefinition {', '\tvar steps []StepDefinition',
              '\tfor _, step := range StepCatalogue() {', '\t\tif step.Owner == "installer" {',
              '\t\t\tsteps = append(steps, step)', '\t\t}', '\t}', '\treturn steps', '}', '']
    for name, field in [('StepLabel', 'label'), ('StepOwner', 'owner')]:
        lines += [f'func {name}(id string) (string, bool) {{', '\tswitch id {']
        for row in rows:
            lines += [f'\tcase {row["symbol"]}:', f'\t\treturn {quote(row[field])}, true']
        lines += ['\tdefault:', '\t\treturn "", false', '\t}', '}', '']
    return subprocess.run(['gofmt'], input='\n'.join(lines), text=True, capture_output=True, check=True).stdout


def shell_source(rows, harness=False):
    lines = ['# Code generated by packaging/generate-steps.py; DO NOT EDIT.',
             '# shellcheck shell=bash disable=SC2034',
             '# Lifecycle states and recovery verdicts are distinct from these phase IDs.', '']
    for owner in OWNERS:
        lines += [f'WOOTC_{owner.upper()}_PHASE_IDS={shlex.quote(chr(10).join(r["id"] for r in rows if r["owner"] == owner))}']
    for name, field in [('wootc_step_label', 'label'), ('wootc_step_owner', 'owner')]:
        lines += ['', f'{name}() {{', '    case "$1" in']
        lines += [f'        {shlex.quote(r["id"])}) printf \'%s\\n\' {shlex.quote(r[field])} ;;' for r in rows]
        lines += ['        *) return 1 ;;', '    esac', '}']
    lines += ['', 'wootc_step_valid() { wootc_step_owner "$1" >/dev/null; }']
    if harness:
        markers = 'phase: (' + '|'.join(r['id'] for r in rows if r['owner'] == 'deployer') + ')([[:space:]]|$)'
        lines += ['', '# All actual deployer phase announcements, not liveness or completion proof.',
                  'WOOTC_DEPLOYER_PHASE_MARKERS=' + shlex.quote(markers)]
        firstboot_markers = 'phase: (' + '|'.join(r['id'] for r in rows if r['owner'] == 'firstboot') + ')([[:space:]]|$)'
        lines += ['WOOTC_FIRSTBOOT_PHASE_MARKERS=' + shlex.quote(firstboot_markers)]
    return '\n'.join(lines) + '\n'


def outputs(rows):
    installer = [{key: row[key] for key in ('id', 'owner', 'label')} for row in rows if row['owner'] == 'installer']
    return {
        'app/steps_gen.go': go_source(rows),
        'app/frontend/src/lib/steps_gen.js': '// Code generated by packaging/generate-steps.py; DO NOT EDIT.\n' +\
            ''.join('export const ' + row['symbol'] + ' = ' + json.dumps(row['id']) + ';\n' for row in rows),
        'payload/steps.sh': shell_source(rows),
        'tests/e2e/steps.sh': shell_source(rows, harness=True),
        'tests/gui/step-catalogue-gen.js': '// Code generated by packaging/generate-steps.py; DO NOT EDIT.\n' +
            'export const INSTALLER_STEP_DEFINITIONS = ' + json.dumps(installer, ensure_ascii=False, indent=2) + ';\n',
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = outputs(read_catalogue(args.root / 'payload/steps.tsv'))
    stale = []
    for name, content in expected.items():
        path = args.root / name
        actual = path.read_text(encoding='utf-8') if path.is_file() else ''
        if actual == content:
            continue
        if args.check:
            stale.append(name)
            sys.stderr.writelines(difflib.unified_diff(actual.splitlines(True), content.splitlines(True),
                                                     fromfile=name, tofile=name + ' (generated)'))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
    if stale:
        sys.exit('Stale generated step vocabulary; run just steps: ' + ', '.join(stale))


if __name__ == '__main__':
    try:
        main()
    except (ValueError, subprocess.CalledProcessError) as exc:
        sys.exit(str(exc))
