$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '../../packaging/winget/verified-tool.ps1')
$temp = Join-Path ([IO.Path]::GetTempPath()) ([guid]::NewGuid().ToString())
New-Item -ItemType Directory -Path $temp | Out-Null
$checks = 0
function Assert-Rejected {
    param([scriptblock]$Action)
    $rejected = $false
    try { & $Action } catch { $rejected = $true }
    if (-not $rejected) { throw 'Untrusted tool was accepted' }
    $script:checks++
}
try {
    $file = Join-Path $temp 'fixture.exe'
    [IO.File]::WriteAllText($file, 'abc')
    # Known SHA256 of the fixture bytes, not a hash generated by the test.
    $expected = 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'
    Assert-ToolHash -Path $file -Expected $expected
    $checks++
    Assert-Rejected { Assert-ToolHash -Path $file -Expected ('0' * 64) }
    Assert-Rejected { Assert-ToolHash -Path $file -Expected '' }
    Assert-Rejected { Assert-ToolHash -Path $file -Expected 'abc' }
    Assert-Rejected { Assert-ToolHash -Path (Join-Path $temp 'absent.exe') -Expected $expected }
    [IO.File]::WriteAllText($file, 'tampered')
    Assert-Rejected { Assert-ToolHash -Path $file -Expected $expected }

    # Execute the actual download path with a bad response. It must refuse
    # and remove the file, rather than return an executable path.
    function Invoke-WebRequest {
        param($Uri, $OutFile, $ErrorAction)
        if ($Uri -notmatch '/releases/download/v1\.12\.13\.0/wingetcreate\.exe$') {
            throw 'Tool URL is not pinned'
        }
        [IO.File]::WriteAllText($OutFile, 'untrusted download')
    }
    Assert-Rejected { Install-VerifiedWingetCreate -Destination $temp }
    if (@(Get-ChildItem -LiteralPath $temp -Directory).Count -ne 0) {
        throw 'Failed verification left an executable behind'
    }
    $checks++
    Remove-Item Function:Invoke-WebRequest
    Write-Host "PASS ($checks checks)"
} finally {
    Remove-Item -LiteralPath $temp -Recurse -Force
}
